### ISSUE TITLE
Speed unreliable on dirt path

### ISSUE THREAD

**Issue by IR0NSIGHT** [Edgeburn/Horse-Highway#10]
i set dirtpath to 40 kph speed, reloaded/restarted server multiple times.
It works somewhat when travellign on our dirtpath roads, but not consistently.

It seems that: when changing from grass->dirt_path it works for a second or so, and then stops working.
I can travel at 40 kph on very small dirtpath roads (probably bc it changes blocktypes often so the 1 second timer never runs out/the recalc speed event is triggered often)
but:
i build a big square of dirt path, and i can only travel at default speed there. 
riding along the edge makes me go to the desired 40 kph

occured on MC 1.19.4, latest spigot

speed config:
BLACK_CONCRETE: 100.0
YELLOW_CONCRETE: 20.0
DIRT_PATH: 40.0
SAND: 25.0
COBBLESTONE: 45.0

**Comment by IR0NSIGHT** [comment]
addon: the speed works as expected with sand, just not the dirt_path 🤷

**Comment by Edgeburn** [comment]
After investigating, I have determined that the bug is with any block with a collision hitbox that is not a full block (such as dirt paths, farmland, slabs, and soul sand; however other "transparent" blocks like glass and glowstone work correctly). For these blocks, it takes the block *underneath* the block, such as the diamond ore shown underneath the farmland in this screenshot. 
![Screenshot 2023-06-03 013707](https://github.com/Edgeburn/Horse-Highway/assets/18710959/291bd9cb-bfc7-4202-9350-020fa6967e14)


~~Until I have fixed this bug, a temporary workaround would be to place a speed block underneath the grass paths.~~ Update posted on [SpigotMC ](https://www.spigotmc.org/resources/horse-highway.100564/)fixing this bug and #9
